export interface Responsavel {
  id: string,
  nome: string,
  nacionalidade: string,
  cpf: string,
  telefone: string,
  email: string,
  dataNascimento: string,
  rg: string,
  logradouro: string,
  numero: string,
  complemento: string,
  bairro: string,
  cep: string,
  cidade: string,
  estado: string,
}